//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRegistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEmployee
    {
        public int EmpolyeeID { get; set; }

        [Required(ErrorMessage = "Please Enter First Name")]
        [StringLength(30, MinimumLength = 3)]

        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Please Enter Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please Enter Date of Birth")]
        [DisplayName("Date of Birth")]
        [DataType(DataType.Date)]       
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> Gender { get; set; }

        [DisplayName("Marrital Status")]
        public Nullable<bool> MarritalStatus { get; set; }

        [DisplayName("Country Name")]
        public Nullable<int> CountryID { get; set; }

        [DisplayName("State Name")]
        public Nullable<int> StateID { get; set; }
        public string Address { get; set; }
        public string Hobbies { get; set; }

        [DisplayName("Country Name")]
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblState tblState { get; set; }

    }
}
